services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend_db:/app/var          
      - jwt_keys:/app/config/jwt   
    environment:
      APP_ENV: prod
      APP_SECRET: change_me_in_production
      DATABASE_URL: sqlite:////app/var/app.db
      JWT_SECRET_KEY: /app/config/jwt/private.pem
      JWT_PUBLIC_KEY: /app/config/jwt/public.pem
      JWT_PASSPHRASE: invoiceapp_jwt_secret
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  backend_db:
  jwt_keys:
